### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by sawyer400** [BeastlyGhost/FNF-BedrockEngine-Legacy#32]
### Describe your bug here.

whenever I open the engine its just a black screen (I mean its playable you just cant see anything)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by sawyer400** [comment]
also my pc is good, it has 1000 gb/1 tb.

**Comment by BeastlyGhost** [comment]
try using this build, I noticed that one of the builds is broken and just returns a black screen
https://github.com/BeastlyGhost/FNF-BedrockEngine-Legacy/actions/runs/1925455924
